---
title: "Quiz Leader Board"
output:
  html_notebook:
    code_folding: hide
  html_document: default
---


```{r notes}

# This is a helper file that make the leader board to show at the end of the quiz. It uses the `googlesheets` package to access the responses and scores and present them in order.

# Notes for the quiz master:
# I have found it easiest to run the set-up chunk ahead of time, then run the get-data chunk, close the output from it, run the leader-board chunk and then click Preview to get the version that is easiest to put up on the screen. I've set it to auto-hide the rest of the code, so all you see is the leaderboard.

```

```{r set-up, echo=FALSE}
# Install any packages you're missing.
# install.packages("googlesheets")
# install.packages("stringr")
# install.packages("dplyr")
# install.packages("knitr")
# install.packages("lubridate")

library(googlesheets)
library(stringr)
library(dplyr)
library(knitr)
library(lubridate)
```

```{r get-data}
data = gs_title("Harry Potter Fanfiction Pub Quiz (Responses)") %>% 
  gs_read()
```

```{r leader-board}
leader_board = data %>% 
  mutate(score_num = as.numeric(str_split_fixed(Score, " / ", 2)[,1])) %>% 
  mutate(date = dmy_hms(Timestamp)) %>% 
  filter(as.Date(date) == today()) %>% # Gets results from today only - delete if all time is okay
  arrange(desc(score_num)) %>% 
  mutate(Rank = as.character(min_rank(desc(score_num)))) %>% 
  select(Rank, `Team Name`, Score)

kable(leader_board)

```



# Thanks for playing!
